Added check for runtime errors in PHP.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -70,7 +70,19 @@ jobs:
           ls -al
 
       # quotes-validate.sh tests essentially the same thing as quotes-examples.sh, but it's geared more for CI.
-      - name: Run the quotes-validate.sh file.  This muse have a 0 exit value or the workflow fails.
+      - name: Run the quotes-validate.sh file.  This must have a 0 exit value or the workflow fails.
         run: |
           chmod +x ./quotes-validate.sh; ./quotes-validate.sh
 
+      # Check for runtime errors.  Copy any string containing a PHP error to errors.txt and return 1 if not empty.  Return 0 otherwise.
+      - name: Check for any PHP errors in the log.
+        run: |
+          grep '\[php:error\]' /var/log/apache2/api_error.log > errors.txt
+          if [ -s errors.txt ]; then 
+            echo "PHP Errors Found:"
+            cat errors.txt
+            exit 1
+          else 
+            echo "No PHP errors found";
+            exit 0
+          fi
